export enum AnalyticsEvent {
  // Page Views
  PAGE_VIEWED = 'PAGE_VIEWED',

  // User Actions
  CV_DOWNLOADED = 'CV_DOWNLOADED',
  PROJECT_OPENED = 'PROJECT_OPENED',
  PROJECT_VIDEO_WATCHED = 'PROJECT_VIDEO_WATCHED',
  GITHUB_LINK_CLICKED = 'GITHUB_LINK_CLICKED',
  SOURCE_CODE_VIEWED = 'SOURCE_CODE_VIEWED',
  YOUTUBE_CHANNEL_OPENED = 'YOUTUBE_CHANNEL_OPENED',
  SOCIAL_LINK_CLICKED = 'SOCIAL_LINK_CLICKED',
  CONTACT_COPIED = 'CONTACT_COPIED',

  // Window Actions
  WINDOW_MINIMIZED = 'WINDOW_MINIMIZED',
  WINDOW_MAXIMIZED = 'WINDOW_MAXIMIZED',
  WINDOW_CLOSED = 'WINDOW_CLOSED',

  // Menu Actions
  CONTEXT_MENU_OPENED = 'CONTEXT_MENU_OPENED',
  FINDER_OPENED = 'FINDER_OPENED',

  // Experience Actions
  EXPERIENCE_DETAILS_EXPANDED = 'EXPERIENCE_DETAILS_EXPANDED',
  EXPERIENCE_DETAILS_COLLAPSED = 'EXPERIENCE_DETAILS_COLLAPSED',

  // Engagement
  SESSION_STARTED = 'SESSION_STARTED',
  FIRST_VISIT = 'FIRST_VISIT',
  PAGE_SCROLLED = 'PAGE_SCROLLED',
  USER_ENGAGED = 'USER_ENGAGED'
}

export interface AnalyticsEventData {
  event: AnalyticsEvent | string;
  metadata?: Record<string, any>;
  value?: number;
}
